package com.donidin.funwithfriends.config;

import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.FloatSliderControllerBuilder;
import dev.isxander.yacl3.api.controller.IntegerSliderControllerBuilder;
import dev.isxander.yacl3.api.controller.TickBoxControllerBuilder;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

public class ModConfigScreen {

    public static Screen createConfigScreen(Screen parent) {
        return YetAnotherConfigLib.createBuilder()
                .title(Component.translatable("config.fun_with_friends.title"))

                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("config.fun_with_friends.category.party"))
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.fun_with_friends.option.party_system"))
                                .description(OptionDescription.of(Component.translatable("config.fun_with_friends.option.party_system.desc")))
                                .binding(true, () -> ModConfig.INSTANCE.enablePartySystem, val -> ModConfig.INSTANCE.enablePartySystem = val)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.fun_with_friends.option.max_party_size"))
                                .description(OptionDescription.of(Component.translatable("config.fun_with_friends.option.max_party_size.desc")))
                                .binding(4, () -> ModConfig.INSTANCE.maxPartySize, val -> ModConfig.INSTANCE.maxPartySize = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(2, 8).step(1))
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.fun_with_friends.option.mount_boost"))
                                .description(OptionDescription.of(Component.translatable("config.fun_with_friends.option.mount_boost.desc")))
                                .binding(true, () -> ModConfig.INSTANCE.enableSharedMountBoost, val -> ModConfig.INSTANCE.enableSharedMountBoost = val)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .build())

                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("config.fun_with_friends.category.interactions"))

                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("config.fun_with_friends.group.item_handing"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("config.fun_with_friends.option.item_handing"))
                                        .description(OptionDescription.of(Component.translatable("config.fun_with_friends.option.item_handing.desc")))
                                        .binding(true, () -> ModConfig.INSTANCE.enableItemHanding, val -> ModConfig.INSTANCE.enableItemHanding = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("config.fun_with_friends.option.item_handing_distance"))
                                        .description(OptionDescription.of(Component.translatable("config.fun_with_friends.option.item_handing_distance.desc")))
                                        .binding(3.0F, () -> (float) ModConfig.INSTANCE.itemHandingReachDistance, val -> ModConfig.INSTANCE.itemHandingReachDistance = val)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(1.0F, 6.0F).step(0.5F))
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("config.fun_with_friends.group.pull_mechanic"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("config.fun_with_friends.option.pull_mechanic"))
                                        .description(OptionDescription.of(Component.translatable("config.fun_with_friends.option.pull_mechanic.desc")))
                                        .binding(true, () -> ModConfig.INSTANCE.enablePullMechanic, val -> ModConfig.INSTANCE.enablePullMechanic = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("config.fun_with_friends.option.pull_distance"))
                                        .description(OptionDescription.of(Component.translatable("config.fun_with_friends.option.pull_distance.desc")))
                                        .binding(3.0F, () -> (float) ModConfig.INSTANCE.pullReachDistance, val -> ModConfig.INSTANCE.pullReachDistance = val)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(1.0F, 6.0F).step(0.5F))
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("config.fun_with_friends.group.health_sharing"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("config.fun_with_friends.option.health_sharing"))
                                        .description(OptionDescription.of(Component.translatable("config.fun_with_friends.option.health_sharing.desc")))
                                        .binding(false, () -> ModConfig.INSTANCE.enableHealthSharing, val -> ModConfig.INSTANCE.enableHealthSharing = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("config.fun_with_friends.option.health_share_amount"))
                                        .description(OptionDescription.of(Component.translatable("config.fun_with_friends.option.health_share_amount.desc")))
                                        .binding(2.0F, () -> ModConfig.INSTANCE.healthShareAmount, val -> ModConfig.INSTANCE.healthShareAmount = val)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(1.0F, 10.0F).step(0.5F))
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("config.fun_with_friends.option.health_share_cooldown"))
                                        .description(OptionDescription.of(Component.translatable("config.fun_with_friends.option.health_share_cooldown.desc")))
                                        .binding(20, () -> ModConfig.INSTANCE.healthShareCooldown, val -> ModConfig.INSTANCE.healthShareCooldown = val)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1, 120).step(1))
                                        .build())
                                .build())

                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.fun_with_friends.option.high_five"))
                                .description(OptionDescription.of(Component.translatable("config.fun_with_friends.option.high_five.desc")))
                                .binding(true, () -> ModConfig.INSTANCE.enableHighFive, val -> ModConfig.INSTANCE.enableHighFive = val)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .build())

                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("config.fun_with_friends.category.throwables"))
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("config.fun_with_friends.group.potato"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("config.fun_with_friends.option.potato_throwing"))
                                        .binding(true, () -> ModConfig.INSTANCE.enablePotatoThrowing, val -> ModConfig.INSTANCE.enablePotatoThrowing = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("config.fun_with_friends.option.potato_cooldown"))
                                        .binding(15, () -> ModConfig.INSTANCE.potatoCooldown, val -> ModConfig.INSTANCE.potatoCooldown = val)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                        .build())
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("config.fun_with_friends.group.slimeball"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("config.fun_with_friends.option.slimeball_throwing"))
                                        .binding(true, () -> ModConfig.INSTANCE.enableSlimeballThrowing, val -> ModConfig.INSTANCE.enableSlimeballThrowing = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("config.fun_with_friends.option.slimeball_cooldown"))
                                        .binding(10, () -> ModConfig.INSTANCE.slimeballCooldown, val -> ModConfig.INSTANCE.slimeballCooldown = val)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                        .build())
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("config.fun_with_friends.group.tnt"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("config.fun_with_friends.option.tnt_throwing"))
                                        .binding(true, () -> ModConfig.INSTANCE.enableTntThrowing, val -> ModConfig.INSTANCE.enableTntThrowing = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("config.fun_with_friends.option.tnt_cooldown"))
                                        .binding(20, () -> ModConfig.INSTANCE.tntThrowCooldown, val -> ModConfig.INSTANCE.tntThrowCooldown = val)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                        .build())
                                .build())
                        .build())

                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("config.fun_with_friends.category.boss_scaling"))
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.fun_with_friends.option.enable_boss_scaling"))
                                .binding(true, () -> ModConfig.INSTANCE.enableBossScaling, val -> ModConfig.INSTANCE.enableBossScaling = val)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("config.fun_with_friends.option.boss_scale_multiplier"))
                                .binding(0.5F, () -> ModConfig.INSTANCE.bossHealthScaleMultiplier, val -> ModConfig.INSTANCE.bossHealthScaleMultiplier = val)
                                .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.1F, 2.0F).step(0.1F))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("config.fun_with_friends.option.boss_max_multiplier"))
                                .binding(3.0F, () -> ModConfig.INSTANCE.bossHealthMaxMultiplier, val -> ModConfig.INSTANCE.bossHealthMaxMultiplier = val)
                                .controller(opt -> FloatSliderControllerBuilder.create(opt).range(1.0F, 10.0F).step(0.5F))
                                .build())
                        .build())

                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("config.fun_with_friends.category.hats"))
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.fun_with_friends.option.enable_hats"))
                                .binding(true, () -> ModConfig.INSTANCE.enableHatEquip, val -> ModConfig.INSTANCE.enableHatEquip = val)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("config.fun_with_friends.group.hat_types"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("config.fun_with_friends.option.allow_banners"))
                                        .binding(true, () -> ModConfig.INSTANCE.allowBannersOnHead, val -> ModConfig.INSTANCE.allowBannersOnHead = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("config.fun_with_friends.option.allow_feathers"))
                                        .binding(true, () -> ModConfig.INSTANCE.allowFeathersOnHead, val -> ModConfig.INSTANCE.allowFeathersOnHead = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("config.fun_with_friends.option.allow_blocks"))
                                        .binding(true, () -> ModConfig.INSTANCE.allowBlocksOnHead, val -> ModConfig.INSTANCE.allowBlocksOnHead = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("config.fun_with_friends.option.allow_candle_stacking"))
                                        .binding(true, () -> ModConfig.INSTANCE.allowCandleStacking, val -> ModConfig.INSTANCE.allowCandleStacking = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        .build())

                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("config.fun_with_friends.category.social"))
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.fun_with_friends.option.typing_indicator"))
                                .binding(true, () -> ModConfig.INSTANCE.enableTypingIndicator, val -> ModConfig.INSTANCE.enableTypingIndicator = val)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.fun_with_friends.option.nick_colors"))
                                .binding(true, () -> ModConfig.INSTANCE.enableCustomNickColors, val -> ModConfig.INSTANCE.enableCustomNickColors = val)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.fun_with_friends.option.chat_emojis"))
                                .binding(true, () -> ModConfig.INSTANCE.enableChatEmojis, val -> ModConfig.INSTANCE.enableChatEmojis = val)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .build())

                .save(ModConfig::save)
                .build()
                .generateScreen(parent);
    }
}